import { useState } from "react";
import Link from "next/link";
import { api } from "@/utils/api";
import { toast } from "sonner";

const initial = { name: "", email: "", phone: "", eventDate: "", eventLocation: "", eventType: "", expectedGuests: 1, service: "Audio DJ" as const, message: "", selectedDj: "DJ Jeff92" as const };
export default function BookUs() {
  const [form, setForm] = useState(initial);
  const create = api.bookings.create.useMutation({ onSuccess: () => { toast.success("“Thank you! Your booking inquiry has been received. We'll get back to you regarding availability and event details.”"); setForm(initial); } });
  const input = (key: keyof typeof form, label: string, type = "text") => <label className="text-sm text-zinc-300">{label}<input type={type} value={form[key]} onChange={event => setForm(value => ({ ...value, [key]: type === "number" ? Number(event.target.value) : event.target.value }))} required className="mt-2 w-full rounded-xl border border-white/10 bg-[#111518] p-3" /></label>;
  return <main className="mx-auto max-w-4xl px-4 py-28 text-white"><h1 className="text-5xl font-black">Book us</h1><p className="mt-3 text-zinc-400">Tell us about your event and preferred DJ service.</p><form onSubmit={event => { event.preventDefault(); create.mutate({ ...form, eventDate: new Date(form.eventDate) }); }} className="mt-8 grid gap-4 rounded-3xl border border-white/10 bg-[#171d20] p-6 md:grid-cols-2">{input("name", "Name")}{input("email", "Email", "email")}{input("phone", "Phone / WhatsApp / Viber")}{input("eventDate", "Event date", "date")}{input("eventLocation", "Event location")}{input("eventType", "Event type")}{input("expectedGuests", "Expected guests", "number")}<label className="text-sm">Service<select value={form.service} onChange={event => setForm(value => ({ ...value, service: event.target.value as typeof form.service }))} className="mt-2 w-full rounded-xl bg-[#111518] p-3">{["Audio DJ","Video DJ","DJ + Percussionist","Others"].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-sm md:col-span-2">Choose DJ<select value={form.selectedDj} onChange={event => setForm(value => ({ ...value, selectedDj: event.target.value as typeof form.selectedDj }))} className="mt-2 w-full rounded-xl bg-[#111518] p-3">{["DJ Jeff92","Ayan Sumania","Jeff92 and Ayan Sumania"].map(value => <option key={value}>{value}</option>)}</select></label><textarea value={form.message} onChange={event => setForm(value => ({ ...value, message: event.target.value }))} placeholder="Tell us about your event (optional)" rows={5} className="rounded-xl bg-[#111518] p-3 md:col-span-2"/><button className="rounded-xl bg-[#B9FF00] px-5 py-3 font-bold text-black md:col-span-2">Send booking request</button></form><div className="mt-6 grid gap-3 sm:grid-cols-2"><Link href="/presskit/jeff92" className="rounded-xl border border-white/10 bg-white/[.03] px-5 py-4 font-semibold hover:border-[#B9FF00]/30">DJ Jeff92 press kit</Link><Link href="/presskit/ayan-sumania" className="rounded-xl border border-white/10 bg-white/[.03] px-5 py-4 font-semibold hover:border-[#B9FF00]/30">Ayan Sumania press kit</Link></div></main>;
}
