export const genreDescriptions: Record<string, string> = {
  "Afro House": "Afro House DJ edits and tracks blending African rhythms with deep and soulful house beats.",
  "Afrobeats": "Afrobeats music featuring modern African pop rhythms, perfect for clubs and dance floors.",
  "Alternative": "Alternative music DJ edits and remixes with unique sounds beyond mainstream genres.",
  "Amapiano": "Amapiano tracks with deep basslines, log drums, and smooth South African grooves.",
  "Bachata": "Bachata DJ edits and remixes with romantic Latin rhythms for dancing.",
  "Baile Funk": "High-energy Baile Funk tracks inspired by Brazilian street and club culture.",
  "Bass House": "Bass House music combining heavy basslines with house grooves for peak-time sets.",
  "Bigroom": "Bigroom EDM tracks designed for festivals, drops, and mainstage energy.",
  "Bmore": "Baltimore Club (Bmore) tracks featuring fast beats and rhythmic vocal chops.",
  "Bollywood": "Bollywood DJ edits and remixes blending Indian music with modern dance beats.",
  "Booty / Miami Bass": "Miami Bass and Booty music with deep bass and classic party energy.",
  "Bounce": "Bounce music with energetic beats, call-and-response vocals, and dancefloor hype.",
  "Breakbeat": "Breakbeat tracks featuring broken rhythms ideal for old-school and modern DJ sets.",
  "Chill / Tropical": "Chill and tropical tracks with relaxed vibes perfect for lounges and beach sets.",
  "Country": "Country music DJ edits blending classic country sounds with modern rhythms.",
  "Dance": "Dance music built for clubs and parties with upbeat and energetic grooves.",
  "Dancehall": "Dancehall tracks with Caribbean vibes and bass-heavy rhythms.",
  "Deep House": "Deep House music featuring soulful melodies and smooth, groovy basslines.",
  "Disco": "Disco tracks and edits inspired by classic 70s dance music and funky rhythms.",
  "Drum & Bass": "Drum and Bass tracks with fast breakbeats and powerful basslines.",
  "Dubstep": "Dubstep music featuring heavy drops, wobble bass, and intense energy.",
  "EDM": "Electronic Dance Music designed for festivals, clubs, and high-energy performances.",
  "Electro": "Electro music with sharp synths and futuristic electronic sounds.",
  "Electro House": "Electro House tracks combining house grooves with aggressive synth leads.",
  "Electronic": "Electronic music covering a wide range of digital and synthesized sounds.",
  "Freestyle": "Freestyle music inspired by classic dance tracks and rhythmic vocal hooks.",
  "Funk": "Funk music with groovy basslines and rhythmic guitar-driven beats.",
  "Funky House": "Funky House tracks blending house beats with funk-inspired grooves.",
  "Future Bass": "Future Bass music with melodic drops and emotional synth progressions.",
  "Future House": "Future House tracks combining bounce basslines with modern house energy.",
  "Future Rave": "Future Rave tracks blending techno and bigroom elements for festival stages.",
  "Guaracha": "Guaracha music with fast-paced Latin rhythms and party-ready energy.",
  "Hard Dance / Style": "Hard Dance tracks featuring aggressive kicks and high-energy tempos.",
  "Hip Hop": "Hip Hop DJ edits and tracks with strong beats and rhythmic vocals.",
  "House": "House music with steady grooves, basslines, and timeless dancefloor appeal.",
  "Indie / Nu Disco": "Indie and Nu Disco tracks blending retro disco vibes with modern sounds.",
  "Jersey Club": "Jersey Club tracks with fast tempos and energetic club rhythms.",
  "K-Pop": "K-Pop DJ edits and remixes featuring Korean pop hits and dance beats.",
  "Latin": "Latin music with energetic rhythms inspired by reggaeton, salsa, and more.",
  "Mainstage": "Mainstage tracks built for festivals with powerful drops and crowd energy.",
  "Mambo": "Mambo music with lively Latin rhythms and classic dance influences.",
  "Melodic House": "Melodic House tracks with emotional melodies and deep progressive vibes.",
  "Moombahton": "Moombahton tracks blending reggaeton rhythms with electronic dance energy.",
  "Pop / Top 40": "Pop and Top 40 DJ edits featuring chart-topping hits for all crowds.",
  "Progressive House": "Progressive House tracks with evolving melodies and uplifting builds.",
  "R&B": "R&B music with smooth vocals and soulful grooves.",
  "Reggae": "Reggae tracks with laid-back rhythms and Caribbean vibes.",
  "Reggaeton": "Reggaeton music featuring Latin beats and club-ready energy.",
  "Rock": "Rock DJ edits blending guitars, drums, and modern remix styles.",
  "Speed House": "Speed House tracks combining fast tempos with heavy basslines.",
  "Tech House": "Tech House music blending house grooves with techno elements.",
  "Techno": "Techno tracks with driving beats and hypnotic rhythms.",
  "Trance": "Trance music featuring uplifting melodies and euphoric builds.",
  "Trap": "Trap tracks with heavy 808s, hi-hats, and aggressive energy.",
  "Tribal House": "Tribal House tracks featuring percussion-driven house rhythms.",
  "Twerk": "Twerk music with bass-heavy beats designed for dancefloor movement.",
  "Uk Garage": "UK Garage tracks with shuffled rhythms and soulful vocals.",
  "Urban": "Urban music blending hip hop, R&B, and modern street sounds."
};
