export const tagDescriptions: Record<string, string> = {
  "2Ks": "Popular DJ edits and remixes from the 2000s era, featuring club hits and dancefloor anthems.",
  "60s": "Classic 1960s tracks reworked into DJ-friendly edits and nostalgic remixes.",
  "70s": "Disco and retro 1970s music transformed into modern DJ edits and party mixes.",
  "80s": "Iconic 1980s hits with extended, remix, and club-style DJ versions.",
  "90s": "Throwback 1990s tracks remixed for DJs, parties, and live mixing.",
  "Acapella": "Clean vocal-only acapellas perfect for mashups, remixes, and DJ blends.",
  "Blend": "Smooth DJ blends designed for seamless transitions between tracks.",
  "Budots": "High-energy Budots DJ edits made for street parties and dance floors.",
  "Christmas": "Holiday-themed DJ edits and remixes perfect for Christmas events and parties.",
  "Epic": "Powerful and cinematic DJ edits with big drops and dramatic builds.",
  "Extended": "Extended DJ versions for better mixing and longer playtime.",
  "Halloween": "Dark and spooky DJ edits and remixes for Halloween parties.",
  "Intro-Outro": "DJ edits with custom intros and outros for smooth mixing and transitions.",
  "Masa": "Crowd-friendly DJ edits made for mass appeal and party vibes.",
  "Mashup": "Creative mashups combining multiple songs into one DJ-friendly track.",
  "Miami-Bass": "Bass-heavy Miami Bass edits inspired by classic club and street sounds.",
  "New-Wave": "New Wave classics reimagined into modern DJ edits and remixes.",
  "NYE": "High-energy DJ tracks perfect for New Year’s Eve countdowns and parties.",
  "Old-School": "Classic old-school tracks remixed for DJs and nostalgic dance floors.",
  "OPM": "Original Pilipino Music (OPM) DJ edits and remixes for Filipino audiences.",
  "Party-Break": "Party break edits designed to hype crowds and boost dancefloor energy.",
  "Redrum": "Hard-hitting DJ edits with reverse, break, and battle-style elements.",
  "Remix": "Creative remixes that refresh popular tracks with new DJ energy.",
  "Short-Edit": "Short and quick DJ edits ideal for fast mixing and radio-style play.",
  "Slam": "Aggressive DJ edits with heavy drops and high-impact transitions.",
  "Throwback": "Nostalgic throwback edits bringing classic hits back to the dancefloor.",
  "Toneplay": "Toneplay DJ edits designed for scratching, routines, and battles.",
  "Transition": "DJ transition tracks built for smooth tempo and genre changes.",
  "Transition-Down": "Transition edits for lowering BPM smoothly during a DJ set.",
  "Transition-Up": "Transition edits for increasing BPM and energy in DJ sets.",
  "Wordplay": "Wordplay DJ edits using lyrical cues for creative transitions."
};
